#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@sysuh3c[-1]
	add ucitrack sysuh3c
	set ucitrack.@sysuh3c[-1].init=sysuh3c
	commit ucitrack
EOF

if ! uci get sysuh3c.@auth[0] 2>/dev/null 1>&2; then
	echo auth section not found
	uci add sysuh3c auth >/dev/null
fi

uci commit sysuh3c

rm -f /tmp/luci-indexcache
exit 0
