#
# Copyright (C) 2008-2017 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for H3C authentication in SYSU
LUCI_DEPENDS:=+sysuh3c

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
